version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 9011:9010
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/student?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: student
      MYSQL_USER: ro
      MYSQL_PASSWORD: Jambalakadijm@43
      MYSQL_ROOT_PASSWORD: Jambalakadijm@43
networks:
  springapimysql-net:
